#ifndef INCLUDED_CHATQT_EXECUTORTYPES_HPP
#define INCLUDED_CHATQT_EXECUTORTYPES_HPP

enum ExecutorType
{
	UNKNOWN_EXECUTORTYPE,
	RECEIVE_MESSAGE,
	PLACEHOLDER_CREATE_USER,
	PLACEHOLDER_FIND_USER
};

#endif
